### ISSUE TITLE
編譯StreamCQL出問題

### ISSUE THREAD

**Issue by fqqgb365** [HuaweiBigData/StreamCQL#14]
求助問題點
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ stream-cql-bianry ---
[INFO] Building jar: D:\stormWorkspace\StreamCQL-master\cql-binary\target\stream-cql-bianry-1.0.jar
[INFO] 
[INFO] --- maven-assembly-plugin:2.3:single (make-assembly) @ stream-cql-bianry ---
[WARNING] The POM for org.apache.maven.plugins:maven-assembly-plugin:jar:2.3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] streamCQL ......................................... SUCCESS [0.155s]
[INFO] streaming-base .................................... SUCCESS [3.666s]
[INFO] stream-storm ...................................... SUCCESS [6.526s]
[INFO] cql ............................................... SUCCESS [4.588s]
[INFO] stream-cql-bianry ................................. FAILURE [0.457s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.508s
[INFO] Finished at: Tue Dec 29 16:24:43 CST 2015
[INFO] Final Memory: 8M/29M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.3:single (make-assembly) on project stream-cql-bianry: Execution make-assembly of goal org.apache.maven.plugins:maven-assembly-plugin:2.3:single failed: A required class was missing while executing org.apache.maven.plugins:maven-assembly-plugin:2.3:single: Lorg/apache/maven/shared/filtering/MavenFileFilter;
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.apache.maven.plugins:maven-assembly-plugin:2.3
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/D:/maven3.2/userLib/org/apache/maven/plugins/maven-assembly-plugin/2.3/maven-assembly-plugin-2.3.jar
[ERROR] urls[1] = file:/D:/maven3.2/userLib/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------: org.apache.maven.shared.filtering.MavenFileFilter
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :stream-cql-bianry

**Comment by makebest** [comment]
i use maven 3.3.3 ,everything is ok. try download and install this version

**Comment by Zhiqiang-He** [comment]
@makebest 
you can try to build again, I also used maven 3.3.3 . and I can build success.

maven-assembly-plugin:2.3 download failed.

**Comment by fqqgb365** [comment]
2015-12-30 09:08:34 | ERROR | [main] | Can't find record writer class. | com.huawei.streaming.cql.executor.operatorinfocreater.OutputInfoCreator (OutputInfoCreator.java:150) 
com.huawei.streaming.cql.exception.ExecutorException: ERROR CQL-04042: Cannot find class 'kafakOutput'.
        at com.huawei.streaming.cql.executor.operatorinfocreater.OutputInfoCreator.createRecordWriterInstance(OutputInfoCreator.java:148) [cql-1.0.jar:na]
        at com.huawei.streaming.cql.executor.operatorinfocreater.OutputInfoCreator.createInstance(OutputInfoCreator.java:67) [cql-1.0.jar:na]
        at com.huawei.streaming.cql.executor.operatorinfocreater.OperatorInfoCreatorFactory.createOperatorInfo(OperatorInfoCreatorFactory.java:66) ~[cql-1.0.jar:na]
        at com.huawei.streaming.cql.executor.ExecutorPlanGenerator.createOperatorInfo(ExecutorPlanGenerator.java:465) ~[cql-1.0.jar:na]
        at com.huawei.streaming.cql.executor.ExecutorPlanGenerator.createOperatorInfos(ExecutorPlanGenerator.java:446) ~[cql-1.0.jar:na]
        at com.huawei.streaming.cql.executor.ExecutorPlanGenerator.parseOperators(ExecutorPlanGenerator.java:139) ~[cql-1.0.jar:na]
        at com.huawei.streaming.cql.executor.ExecutorPlanGenerator.generate(ExecutorPlanGenerator.java:107) ~[cql-1.0.jar:na]
        at com.huawei.streaming.cql.executor.PhysicalPlanExecutor.generatorPlan(PhysicalPlanExecutor.java:238) ~[cql-1.0.jar:na]
        at com.huawei.streaming.cql.executor.PhysicalPlanExecutor.execute(PhysicalPlanExecutor.java:138) ~[cql-1.0.jar:na]
        at com.huawei.streaming.cql.tasks.SubmitTask.submitApplication(SubmitTask.java:167) ~[cql-1.0.jar:na]
        at com.huawei.streaming.cql.tasks.SubmitTask.execute(SubmitTask.java:105) ~[cql-1.0.jar:na]
        at com.huawei.streaming.cql.Driver.executeTask(Driver.java:222) ~[cql-1.0.jar:na]
        at com.huawei.streaming.cql.Driver.run(Driver.java:152) ~[cql-1.0.jar:na]
        at com.huawei.streaming.cql.CQLClient.processCQL(CQLClient.java:288) ~[cql-1.0.jar:na]
        at com.huawei.streaming.cql.CQLClient.processLine(CQLClient.java:233) ~[cql-1.0.jar:na]
        at com.huawei.streaming.cql.CQLClient.readConconsole(CQLClient.java:193) ~[cql-1.0.jar:na]
        at com.huawei.streaming.cql.CQLClient.executeDriver(CQLClient.java:158) ~[cql-1.0.jar:na]
        at com.huawei.streaming.cql.CQLClient.main(CQLClient.java:93) ~[cql-1.0.jar:na]

**Comment by Zhiqiang-He** [comment]
@fqqgb365 
kafakOutput is wrong, you should use "kafkaoutput"

**Comment by Zhiqiang-He** [comment]
@fqqgb365 
I already fix kafka example issues. you can try it again.

**Comment by fqqgb365** [comment]
@Zhiqiang-He 
非常感谢你的解答,例子是运行起来的,但是topic = "cqlOut"没有结果显示，不知道怎么回事？
我按以下例子执行的
1）  首先创建一个输入流s1，使用默认的反序列化方式来解析数据。

  CREATE INPUT STREAM s1  -- 指定输入流的名称
  (id INT, name STRING, type INT)  -- 流中字段类型
  SOURCE KafkaInput  -- 指定数据源及相关的属性
  PROPERTIES (groupid = "cqlClient", topic = "cqlInput",
  zookeepers = "127.0.0.1:2181", brokers = "127.0.0.1:9092" );
2）  然后创建输出流，使用默认的序列化方式输出数据。

  CREATE OUTPUT STREAM s2  -- 指定输出流的名称
  (cnt LONG)  -- 流中字段类型
  SINK kafakOutput  -- 指定数据目的及相关属性
  PROPERTIES ( topic = "cqlOut", zookeepers = "127.0.0.1:2181",
  brokers = "127.0.0.1:9092" );
3）  接下来，执行从输入流转化到输出流的StreamCQL语句，这个例子中只是统计事件的条数。

  INSERT INTO STREAM s2 SELECT count(*) FROM s1;
4）  最后，将上述语句构成的StreamCQL应用程序进行提交，并指定这个应用程序名称为cql_kafka_example。一旦提交，系统就开始进行应用程序的解析和发布。

  SUBMIT APPLICATION cql_kafka_example;

==================================================================

以下是我的logs信息
2015-12-31 00:50:34 | INFO  | [main] | Submitting topology cql_kafka in distributed mode with conf {"drpc.worker.threads":64,"ui.actions.enabled":true,"ui.filter.params":null,"topology.state.synchronization.timeout.secs":60,"topology.executor.send.buffer.size":1024,"topology.worker.childopts":null,"storm.messaging.netty.max_retries":300,"worker.gc.childopts":"","topology.max.spout.pending":null,"storm.auth.simple-acl.users":[],"storm.zookeeper.retry.intervalceiling.millis":30000,"zmq.hwm":0,"ui.users":null,"drpc.authorizer.acl.filename":"drpc-auth-acl.yaml","drpc.https.keystore.type":"JKS","topology.message.timeout.secs":30,"topology.max.task.parallelism":null,"topology.spout.wait.strategy":"backtype.storm.spout.SleepSpoutWaitStrategy","nimbus.credential.renewers.freq.secs":600,"storm.zookeeper.auth.password":null,"supervisor.slots.ports":[6700,6701,6702,6703],"storm.group.mapping.service":"backtype.storm.security.auth.ShellBasedGroupsMapping","storm.zookeeper.servers":["127.0.0.1"],"transactional.zookeeper.servers":null,"supervisor.childopts":"-Xmx256m","drpc.https.keystore.password":"","nimbus.host":"127.0.0.1","storm.cluster.mode":"distributed","ui.childopts":"-Xmx768m","topology.disruptor.wait.strategy":"com.lmax.disruptor.BlockingWaitStrategy","topology.enable.message.timeouts":true,"logviewer.appender.name":"A1","storm.auth.simple-white-list.users":[],"storm.local.mode.zmq":false,"drpc.request.timeout.secs":600,"drpc.https.port":-1,"topology.multilang.serializer":"backtype.storm.multilang.JsonSerializer","storm.zookeeper.root":"\/storm","storm.thrift.transport":"backtype.storm.security.auth.SimpleTransportPlugin","task.credentials.poll.secs":30,"topology.debug":false,"supervisor.enable":true,"nimbus.thrift.port":6627,"topology.sleep.spout.wait.strategy.time.ms":1,"nimbus.reassign":true,"storm.zookeeper.connection.timeout":30000,"drpc.http.port":3774,"supervisor.heartbeat.frequency.secs":5,"topology.worker.shared.thread.pool.size":4,"zmq.threads":1,"storm.nimbus.retry.intervalceiling.millis":60000,"topology.bolts.outgoing.overflow.buffer.enable":false,"topology.acker.executors":null,"dev.zookeeper.path":"\/tmp\/dev-storm-zookeeper","storm.group.mapping.service.cache.duration.secs":120,"transactional.zookeeper.root":"\/transactional","worker.heartbeat.frequency.secs":1,"nimbus.supervisor.timeout.secs":60,"nimbus.thrift.max_buffer_size":1048576,"storm.local.dir":"storm-local","storm.auth.simple-acl.admins":[],"task.refresh.poll.secs":10,"supervisor.worker.timeout.secs":30,"topology.tick.tuple.freq.secs":null,"storm.messaging.netty.client_worker_threads":1,"nimbus.file.copy.expiration.secs":600,"nimbus.task.timeout.secs":30,"topology.builtin.metrics.bucket.size.secs":60,"storm.messaging.transport":"backtype.storm.messaging.netty.Context","topology.transfer.buffer.size":1024,"drpc.childopts":"-Xmx768m","ui.host":"0.0.0.0","topology.workers":1,"supervisor.monitor.frequency.secs":3,"transactional.zookeeper.port":null,"storm.messaging.netty.server_worker_threads":1,"topology.max.error.report.per.interval":5,"storm.messaging.netty.transfer.batch.size":262144,"storm.zookeeper.topology.auth.scheme":"digest","storm.messaging.netty.buffer_size":5242880,"supervisor.run.worker.as.user":false,"storm.messaging.netty.min_wait_ms":100,"supervisor.supervisors":[],"nimbus.childopts":"-Xmx1024m","storm.principal.tolocal":"backtype.storm.security.auth.DefaultPrincipalToLocal","supervisor.supervisors.commands":[],"topology.skip.missing.kryo.registrations":false,"topology.trident.batch.emit.interval.millis":500,"topology.testing.always.try.serialize":false,"logs.users":null,"storm.nimbus.retry.times":5,"worker.childopts":"-Xmx768m","topology.stats.sample.rate":0.05,"drpc.authorizer.acl.strict":false,"ui.http.creds.plugin":"backtype.storm.security.auth.DefaultHttpCredentialsPlugin","storm.zookeeper.topology.auth.payload":"-8601095714988457974:-8672045687202275723","topology.environment":null,"storm.zookeeper.port":2181,"supervisor.worker.start.timeout.secs":120,"nimbus.cleanup.inbox.freq.secs":600,"topology.kryo.factory":"backtype.storm.serialization.DefaultKryoFactory","ui.filter":null,"task.heartbeat.frequency.secs":3,"topology.fall.back.on.java.serialization":true,"logviewer.cleanup.age.mins":10080,"topology.worker.receiver.thread.count":1,"drpc.http.creds.plugin":"backtype.storm.security.auth.DefaultHttpCredentialsPlugin","logviewer.port":8000,"ui.port":8080,"storm.messaging.netty.authentication":false,"storm.zookeeper.retry.times":5,"topology.tuple.serializer":"backtype.storm.serialization.types.ListDelegateSerializer","ui.header.buffer.bytes":4096,"storm.messaging.netty.max_wait_ms":1000,"topology.error.throttle.interval.secs":10,"nimbus.task.launch.secs":120,"drpc.port":3772,"task.kill.wait.seconds":3,"storm.auth.simple-acl.users.commands":[],"storm.zookeeper.session.timeout":30000,"drpc.invocations.port":3773,"logviewer.childopts":"-Xmx128m","java.library.path":"\/usr\/local\/lib:\/opt\/local\/lib:\/usr\/lib","storm.meta.serialization.delegate":"backtype.storm.serialization.GzipThriftSerializationDelegate","storm.messaging.netty.flush.check.interval.ms":10,"zmq.linger.millis":5000,"nimbus.topology.validator":"backtype.storm.nimbus.DefaultTopologyValidator","nimbus.monitor.freq.secs":10,"topology.executor.receive.buffer.size":1024,"topology.tasks":null,"storm.zookeeper.retry.interval":1000,"drpc.invocations.threads":64,"nimbus.inbox.jar.expiration.secs":3600,"topology.classpath":null,"storm.nimbus.retry.interval.millis":2000,"storm.messaging.netty.socket.backlog":500,"drpc.queue.size":128,"supervisor.worker.shutdown.sleep.secs":1,"nimbus.thrift.threads":64,"storm.zookeeper.auth.user":null,"drpc.max_buffer_size":1048576} | backtype.storm.StormSubmitter (StormSubmitter.java:231) 
2015-12-31 00:50:34 | INFO  | [main] | Finished submitting topology: cql_kafka | backtype.storm.StormSubmitter (StormSubmitter.java:248) 
2015-12-31 00:50:34 | INFO  | [main] | delete user packed jar after submit | com.huawei.streaming.cql.executor.PhysicalPlanExecutor (PhysicalPlanExecutor.java:156) 
2015-12-31 00:50:34 | INFO  | [main] | unRegister jars from class loader. | com.huawei.streaming.cql.DriverContext (DriverContext.java:427)

**Comment by Zhiqiang-He** [comment]
@fqqgb365 
任务提交之后，StreamCQL就已经关闭和storm的连接，具体数据的输出，取决于语句中的定义。
在你的示例中，数据被输出到了kafka中名称为cqlOut的topic。如果kafka中没有数据输出的话，可以在storm UI看下拓扑是否异常，以及看下storm worker的日志。

**Comment by fqqgb365** [comment]
@Zhiqiang-He 
非常感谢你的帮助,例如终于运行起来,很不容易的，呵呵
有什么好建设学好StreamCQL？ 或者提供更丰富的例子来学习？

**Comment by Zhiqiang-He** [comment]
StreamCQL的语言和SQL类似，本身就是为了减少学习成本的，和传统SQL的区别就在窗口、输入输出、序列化反序列化部分。这几部分只要熟悉了，其他方面都可以很快上手。
StreamCQL的doc目录提供的CQL语法手册，相关其他方面的语法说明可以参照该文档。
如果已经有可以用来测试的业务，可以试着用CQL来改写，二者对比下，然后就可以发现CQL在业务编写方面的便捷。如果发现了其他问题或者有新的需求，也欢迎提出来，如果能够一起合作开发，将StreamCQL发展的更加完善，我们一定更加欢迎。

**Comment by fqqgb365** [comment]
@Zhiqiang-He 
目前只是把StreamCQL运行起来, 还没有具体深入了解, 感觉窗口模式跟oracle的分析函数差不多，
目前都是自己在研究，公司还没有涉及到大数据相关的。还处于学习者啊

**Comment by Zhiqiang-He** [comment]
@fqqgb365 
窗口模式确实和oracle的over这类窗口函数概念上差不多，但是在流上面，又多了新数据和旧数据的区别，窗口是一个管道，新数据进来，旧数据出去，新和旧数据都会导致窗口内数据统计结果发生变化。所以会比oracle稍微复杂一些。
在CQL的设计上，已经从语法上屏蔽了新数据和旧数据的相关语法，用户完全不需要感知，在初次接触窗口的过程中，会感觉更加简单，易懂。

**Comment by fqqgb365** [comment]
@Zhiqiang-He 
所以说你们是高手啊，把复杂的东西简单化，跟hive把mapreduce一样的原理,StreamCQL还能应用在spark？

**Comment by Zhiqiang-He** [comment]
@fqqgb365 
StreamCQL底层是解耦的，所以理论上可以应用在Spark Streaming上面。但是需要做适配。不过目前我们主要以Storm为主，重点是发展StreamCQL的功能，我们也欢迎其他人来进行spark Streaming的适配。
