### ISSUE TITLE
An error has occurred,NoClassDefFoundError: clojure/lang/IFn

### ISSUE THREAD

**Issue by makebest** [HuaweiBigData/StreamCQL#15]
hi,i tested with examples, an error occurred.
it using the local mode.
i have set the attribute value of "streaming.storm.submit.islocal" to "true" in streaming-site.xml.
what's wrong?i don't know why.
here is cql log:
2015-12-29 02:30:11 | INFO  | [main] | start to parse cql : CREATE INPUT STREAM s
    (id INT, name STRING, type INT)
SOURCE randomgen
    PROPERTIES ( timeUnit = "SECONDS", period = "1",
        eventNumPerperiod = "1", isSchedule = "true" ) | com.huawei.streaming.cql.semanticanalyzer.parser.ApplicationParser (ApplicationParser.java:44) 
2015-12-29 02:30:11 | INFO  | [main] | Parse Completed | com.huawei.streaming.cql.semanticanalyzer.parser.ApplicationParser (ApplicationParser.java:69) 
2015-12-29 02:30:11 | INFO  | [main] | start to execute CREATE INPUT STREAM s (id INT, name STRING, type INT) SOURCE randomgen PROPERTIES ( 'timeUnit' = 'SECONDS', 'period' = '1', 'eventNumPerperiod' = '1', 'isSchedule' = 'true' ) | com.huawei.streaming.cql.tasks.LazyTask (LazyTask.java:62) 
2015-12-29 02:30:11 | INFO  | [main] | start to parse cql : CREATE OUTPUT STREAM rs
    (type INT, cc INT)
SINK consoleOutput | com.huawei.streaming.cql.semanticanalyzer.parser.ApplicationParser (ApplicationParser.java:44) 
2015-12-29 02:30:11 | INFO  | [main] | Parse Completed | com.huawei.streaming.cql.semanticanalyzer.parser.ApplicationParser (ApplicationParser.java:69) 
2015-12-29 02:30:11 | INFO  | [main] | start to execute CREATE OUTPUT STREAM rs (type INT, cc INT) SINK consoleOutput | com.huawei.streaming.cql.tasks.LazyTask (LazyTask.java:62) 
2015-12-29 02:30:11 | INFO  | [main] | start to parse cql : INSERT INTO STREAM rs SELECT type, COUNT(id) as cc
    FROM s[RANGE 20 SECONDS BATCH]
    WHERE id > 5 GROUP BY type | com.huawei.streaming.cql.semanticanalyzer.parser.ApplicationParser (ApplicationParser.java:44) 
2015-12-29 02:30:11 | INFO  | [main] | Parse Completed | com.huawei.streaming.cql.semanticanalyzer.parser.ApplicationParser (ApplicationParser.java:69) 
2015-12-29 02:30:11 | INFO  | [main] | start to execute INSERT INTO STREAM rs SELECT type, count(id) AS cc FROM s[RANGE 20 SECONDS BATCH] WHERE id > 5 GROUP BY type | com.huawei.streaming.cql.tasks.LazyTask (LazyTask.java:62) 
2015-12-29 02:30:14 | INFO  | [main] | start to parse cql : SUBMIT APPLICATION example | com.huawei.streaming.cql.semanticanalyzer.parser.ApplicationParser (ApplicationParser.java:44) 
2015-12-29 02:30:14 | INFO  | [main] | Parse Completed | com.huawei.streaming.cql.semanticanalyzer.parser.ApplicationParser (ApplicationParser.java:69) 
2015-12-29 02:30:14 | INFO  | [main] | combine all split contexts | com.huawei.streaming.cql.builder.operatorsplitter.OperatorSplitter (OperatorCombiner.java:101) 
2015-12-29 02:30:14 | INFO  | [main] | Using defaults.yaml from resources | backtype.storm.utils.Utils (Utils.java:253) 
2015-12-29 02:30:14 | INFO  | [main] | Using defaults.yaml from resources | backtype.storm.utils.Utils (Utils.java:253) 
2015-12-29 02:30:14 | INFO  | [main] | The baseSleepTimeMs [2000] the maxSleepTimeMs [60000] the maxRetries [5] | backtype.storm.utils.StormBoundedExponentialBackoffRetry (StormBoundedExponentialBackoffRetry.java:47) 
2015-12-29 02:30:30 | ERROR | [main] | Failed to connect to application server. | com.huawei.streaming.storm.StormApplication (StormApplication.java:153) 
2015-12-29 02:30:30 | INFO  | [main] | unRegister jars from class loader. | com.huawei.streaming.cql.DriverContext (DriverContext.java:427) 
2015-12-29 02:30:30 | ERROR | [main] | Failed to execute cql SUBMIT APPLICATION example | com.huawei.streaming.cql.CQLClient (CQLClient.java:296) 
2015-12-29 02:32:54 | INFO  | [main] | start to parse cql : CREATE INPUT STREAM s
    (id INT, name STRING, type INT)
SOURCE randomgen
    PROPERTIES ( timeUnit = "SECONDS", period = "1",
        eventNumPerperiod = "1", isSchedule = "true" ) | com.huawei.streaming.cql.semanticanalyzer.parser.ApplicationParser (ApplicationParser.java:44) 
2015-12-29 02:32:54 | INFO  | [main] | Parse Completed | com.huawei.streaming.cql.semanticanalyzer.parser.ApplicationParser (ApplicationParser.java:69) 
2015-12-29 02:32:54 | INFO  | [main] | start to execute CREATE INPUT STREAM s (id INT, name STRING, type INT) SOURCE randomgen PROPERTIES ( 'timeUnit' = 'SECONDS', 'period' = '1', 'eventNumPerperiod' = '1', 'isSchedule' = 'true' ) | com.huawei.streaming.cql.tasks.LazyTask (LazyTask.java:62) 
2015-12-29 02:32:54 | INFO  | [main] | start to parse cql : CREATE OUTPUT STREAM rs
    (type INT, cc INT)
SINK consoleOutput | com.huawei.streaming.cql.semanticanalyzer.parser.ApplicationParser (ApplicationParser.java:44) 
2015-12-29 02:32:54 | INFO  | [main] | Parse Completed | com.huawei.streaming.cql.semanticanalyzer.parser.ApplicationParser (ApplicationParser.java:69) 
2015-12-29 02:32:54 | INFO  | [main] | start to execute CREATE OUTPUT STREAM rs (type INT, cc INT) SINK consoleOutput | com.huawei.streaming.cql.tasks.LazyTask (LazyTask.java:62) 
2015-12-29 02:32:54 | INFO  | [main] | start to parse cql : INSERT INTO STREAM rs SELECT type, COUNT(id) as cc
    FROM s[RANGE 20 SECONDS BATCH]
    WHERE id > 5 GROUP BY type | com.huawei.streaming.cql.semanticanalyzer.parser.ApplicationParser (ApplicationParser.java:44) 
2015-12-29 02:32:54 | INFO  | [main] | Parse Completed | com.huawei.streaming.cql.semanticanalyzer.parser.ApplicationParser (ApplicationParser.java:69) 
2015-12-29 02:32:54 | INFO  | [main] | start to execute INSERT INTO STREAM rs SELECT type, count(id) AS cc FROM s[RANGE 20 SECONDS BATCH] WHERE id > 5 GROUP BY type | com.huawei.streaming.cql.tasks.LazyTask (LazyTask.java:62) 
2015-12-29 02:32:54 | INFO  | [main] | start to parse cql : SUBMIT APPLICATION example | com.huawei.streaming.cql.semanticanalyzer.parser.ApplicationParser (ApplicationParser.java:44) 
2015-12-29 02:32:54 | INFO  | [main] | Parse Completed | com.huawei.streaming.cql.semanticanalyzer.parser.ApplicationParser (ApplicationParser.java:69) 
2015-12-29 02:32:54 | INFO  | [main] | combine all split contexts | com.huawei.streaming.cql.builder.operatorsplitter.OperatorSplitter (OperatorCombiner.java:101) 
2015-12-29 02:32:54 | INFO  | [main] | start to execute application example | com.huawei.streaming.cql.executor.PhysicalPlanExecutor (PhysicalPlanExecutor.java:127) 
2015-12-29 02:32:54 | INFO  | [main] | start to unzip jar stream-storm-1.0-jar-with-dependencies.jar | com.huawei.streaming.cql.executor.mergeuserdefinds.JarExpander (JarExpander.java:79) 
2015-12-29 02:32:54 | INFO  | [main] | unzip jar D:\Users\xiang.zhang\AppData\Local\Temp\d5f22acc40c347f198cf728e49b1e754\stream-storm-1.0-jar-with-dependencies.jar to D:\Users\xiang.zhang\AppData\Local\Temp\d5f22acc40c347f198cf728e49b1e754\jartmp | com.huawei.streaming.cql.executor.mergeuserdefinds.JarExpander (JarExpander.java:91) 
2015-12-29 02:33:17 | INFO  | [main] | finished to unzip jar to dir | com.huawei.streaming.cql.executor.mergeuserdefinds.JarExpander (JarExpander.java:84) 
2015-12-29 02:33:17 | INFO  | [main] | start to copy ch | com.huawei.streaming.cql.executor.mergeuserdefinds.JarFilesMerger (JarFilesMerger.java:82) 
2015-12-29 02:33:19 | INFO  | [main] | start to copy com | com.huawei.streaming.cql.executor.mergeuserdefinds.JarFilesMerger (JarFilesMerger.java:82) 
2015-12-29 02:33:36 | INFO  | [main] | start to copy darwin | com.huawei.streaming.cql.executor.mergeuserdefinds.JarFilesMerger (JarFilesMerger.java:82) 
2015-12-29 02:33:36 | INFO  | [main] | start to copy jline | com.huawei.streaming.cql.executor.mergeuserdefinds.JarFilesMerger (JarFilesMerger.java:82) 
2015-12-29 02:33:36 | INFO  | [main] | start to copy joptsimple | com.huawei.streaming.cql.executor.mergeuserdefinds.JarFilesMerger (JarFilesMerger.java:82) 
2015-12-29 02:33:37 | INFO  | [main] | start to copy kafka | com.huawei.streaming.cql.executor.mergeuserdefinds.JarFilesMerger (JarFilesMerger.java:82) 
2015-12-29 02:33:53 | INFO  | [main] | start to copy linux | com.huawei.streaming.cql.executor.mergeuserdefinds.JarFilesMerger (JarFilesMerger.java:82) 
2015-12-29 02:33:53 | INFO  | [main] | start to copy META-INF | com.huawei.streaming.cql.executor.mergeuserdefinds.JarFilesMerger (JarFilesMerger.java:82) 
2015-12-29 02:33:54 | INFO  | [main] | start to copy net | com.huawei.streaming.cql.executor.mergeuserdefinds.JarFilesMerger (JarFilesMerger.java:82) 
2015-12-29 02:33:56 | INFO  | [main] | start to copy org | com.huawei.streaming.cql.executor.mergeuserdefinds.JarFilesMerger (JarFilesMerger.java:82) 
2015-12-29 02:34:06 | INFO  | [main] | start to copy scala | com.huawei.streaming.cql.executor.mergeuserdefinds.JarFilesMerger (JarFilesMerger.java:82) 
2015-12-29 02:34:26 | INFO  | [main] | start to copy win32 | com.huawei.streaming.cql.executor.mergeuserdefinds.JarFilesMerger (JarFilesMerger.java:82) 
2015-12-29 02:34:44 | INFO  | [main] | finished to package jar | com.huawei.streaming.cql.executor.mergeuserdefinds.JarPacker (JarPacker.java:68) 
2015-12-29 02:34:49 | INFO  | [main] | start to generator executor application for app example | com.huawei.streaming.cql.executor.ExecutorPlanGenerator (ExecutorPlanGenerator.java:102) 
2015-12-29 02:34:49 | INFO  | [main] | AddEventType enter, the eventtypeName is:s. | com.huawei.streaming.event.EventTypeMng (EventTypeMng.java:73) 
2015-12-29 02:34:49 | INFO  | [main] | AddEventType enter, the eventtypeName is:rs. | com.huawei.streaming.event.EventTypeMng (EventTypeMng.java:73) 
2015-12-29 02:34:49 | INFO  | [main] | start to parse cql : (s.id > 5) | com.huawei.streaming.cql.semanticanalyzer.parser.ApplicationParser (ApplicationParser.java:44) 
2015-12-29 02:34:49 | INFO  | [main] | Parse Completed | com.huawei.streaming.cql.semanticanalyzer.parser.ApplicationParser (ApplicationParser.java:69) 
2015-12-29 02:34:49 | INFO  | [main] | start to create binary Expressions. | com.huawei.streaming.cql.executor.expressioncreater.PropertyValueExpressionCreator (BinaryExpressionCreator.java:54) 
2015-12-29 02:34:49 | INFO  | [main] | Parse Completed, cql : s.type,  count( s.id )  | com.huawei.streaming.cql.semanticanalyzer.parser.SelectClauseParser (SelectClauseParser.java:68) 
2015-12-29 02:34:49 | INFO  | [main] | start to parse cql : s.type | com.huawei.streaming.cql.semanticanalyzer.parser.GroupbyClauseParser (GroupbyClauseParser.java:45) 
2015-12-29 02:34:49 | INFO  | [main] | Parse Completed | com.huawei.streaming.cql.semanticanalyzer.parser.GroupbyClauseParser (GroupbyClauseParser.java:68) 
2015-12-29 02:34:49 | INFO  | [main] | start to parse cql : s.type | com.huawei.streaming.cql.semanticanalyzer.parser.GroupbyClauseParser (GroupbyClauseParser.java:45) 
2015-12-29 02:34:49 | INFO  | [main] | Parse Completed | com.huawei.streaming.cql.semanticanalyzer.parser.GroupbyClauseParser (GroupbyClauseParser.java:68) 
2015-12-29 02:34:49 | INFO  | [main] | start to create aggregate service | com.huawei.streaming.cql.executor.operatorviewscreater.AggregateServiceViewCreator (AggregateServiceViewCreator.java:89) 
2015-12-29 02:34:49 | INFO  | [main] | start to submit application example | com.huawei.streaming.cql.executor.PhysicalPlanExecutor (PhysicalPlanExecutor.java:201) 
2015-12-29 02:34:49 | INFO  | [main] | reset submit jar to D:\Users\xiang.zhang\AppData\Local\Temp\example.ee15c039adeb456ea109245ae7fd200a.jar | com.huawei.streaming.storm.StormApplication (StormApplication.java:314) 
2015-12-29 02:34:49 | INFO  | [main] | Using defaults.yaml from resources | backtype.storm.utils.Utils (Utils.java:253) 
2015-12-29 02:34:49 | INFO  | [main] | Using defaults.yaml from resources | backtype.storm.utils.Utils (Utils.java:253) 
2015-12-29 02:34:49 | INFO  | [main] | GenFunctionOpsOrder enter. | com.huawei.streaming.application.OperatorMng (OperatorMng.java:205) 
2015-12-29 02:34:49 | INFO  | [main] | delete user packed jar after submit | com.huawei.streaming.cql.executor.PhysicalPlanExecutor (PhysicalPlanExecutor.java:156) 
2015-12-29 02:34:49 | INFO  | [main] | unRegister jars from class loader. | com.huawei.streaming.cql.DriverContext (DriverContext.java:427) 
2015-12-29 02:34:49 | ERROR | [main] | Failed to execute cql SUBMIT APPLICATION example | com.huawei.streaming.cql.CQLClient (CQLClient.java:308) 
java.lang.NoClassDefFoundError: clojure/lang/IFn
    at com.huawei.streaming.storm.StormApplication.localLaunch(StormApplication.java:519) ~[stream-storm-1.0.jar:na]
    at com.huawei.streaming.storm.StormApplication.launch(StormApplication.java:105) ~[stream-storm-1.0.jar:na]
    at com.huawei.streaming.cql.executor.PhysicalPlanExecutor.submit(PhysicalPlanExecutor.java:209) ~[cql-1.0.jar:na]
    at com.huawei.streaming.cql.executor.PhysicalPlanExecutor.execute(PhysicalPlanExecutor.java:139) ~[cql-1.0.jar:na]
    at com.huawei.streaming.cql.tasks.SubmitTask.submitApplication(SubmitTask.java:167) ~[cql-1.0.jar:na]
    at com.huawei.streaming.cql.tasks.SubmitTask.execute(SubmitTask.java:105) ~[cql-1.0.jar:na]
    at com.huawei.streaming.cql.Driver.executeTask(Driver.java:222) ~[cql-1.0.jar:na]
    at com.huawei.streaming.cql.Driver.run(Driver.java:152) ~[cql-1.0.jar:na]
    at com.huawei.streaming.cql.CQLClient.processCQL(CQLClient.java:288) [cql-1.0.jar:na]
    at com.huawei.streaming.cql.CQLClient.processLine(CQLClient.java:233) [cql-1.0.jar:na]
    at com.huawei.streaming.cql.CQLClient.readConconsole(CQLClient.java:193) [cql-1.0.jar:na]
    at com.huawei.streaming.cql.CQLClient.executeDriver(CQLClient.java:158) [cql-1.0.jar:na]
    at com.huawei.streaming.cql.CQLClient.main(CQLClient.java:93) [cql-1.0.jar:na]
Caused by: java.lang.ClassNotFoundException: clojure.lang.IFn
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[na:1.7.0_25]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_25]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_25]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.7.0_25]
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.7.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.7.0_25]
    ... 13 common frames omitted

**Comment by Zhiqiang-He** [comment]
StreamCQL is not support running local model. because many clojure jar was exclude in pom.
streaming.storm.submit.islocal is only used in unit test.
