### ISSUE TITLE
mvn clean install失败

### ISSUE THREAD

**Issue by xiao321** [HuaweiBigData/StreamCQL#30]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] streamCQL .......................................... SUCCESS [  0.413 s]
[INFO] streaming-base ..................................... SUCCESS [  9.629 s]
[INFO] stream-storm ....................................... SUCCESS [ 12.255 s]
[INFO] cql ................................................ FAILURE [ 15.418 s]
[INFO] stream-cql-bianry .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 37.965 s
[INFO] Finished at: 2016-08-04T14:44:23+08:00
[INFO] Final Memory: 21M/696M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project cql: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/zhouyu/workspace/StreamCQL/cql/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :cql

**Comment by xiao321** [comment]
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ stream-cql-bianry ---
[INFO] Installing /home/xiaobingxian/workspace/StreamCQL/cql-binary/target/stream-cql-bianry-1.0.jar to /home/xiaobingxian/.m2/repository/com/huawei/streaming/stream-cql-bianry/1.0/stream-cql-bianry-1.0.jar
[INFO] Installing /home/xiaobingxian/workspace/StreamCQL/cql-binary/pom.xml to /home/xiaobingxian/.m2/repository/com/huawei/streaming/stream-cql-bianry/1.0/stream-cql-bianry-1.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] streamCQL .......................................... SUCCESS [  0.347 s]
[INFO] streaming-base ..................................... SUCCESS [  9.948 s]
[INFO] stream-storm ....................................... SUCCESS [ 12.729 s]
[INFO] cql ................................................ SUCCESS [ 39.734 s]
[INFO] stream-cql-bianry .................................. SUCCESS [01:56 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] 
[INFO] Total time: 02:59 min
[INFO] Finished at: 2016-08-04T15:08:45+08:00
[INFO] Final Memory: 28M/990M
[INFO] ------------------------------------------------------------------------

我是单机测试，在编译streamcql，服务器上启动着kafka/zookeeper/storm，产生我上述的端口占用问题，导致出现一些问题。在我杀死kafka/zookeeper/storm的进程后，可以正常编译。但还是有一些问题
2016-08-04 07:06:28 | INFO  | [main] | Parse Completed | com.huawei.streaming.cql.semanticanalyzer.parser.ApplicationParser (ApplicationParser.java:69) 
2016-08-04 07:06:28 | ERROR | [main] | Can't find schema by name. | com.huawei.streaming.cql.semanticanalyzer.BaseAnalyzer (BaseAnalyzer.java:140) 
com.huawei.streaming.cql.exception.SemanticAnalyzerException: ERROR CQL-04008: Cannot find stream 's2'.
	at com.huawei.streaming.cql.semanticanalyzer.BaseAnalyzer.getSchemaByName(BaseAnalyzer.java:138) ~[classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.FromClauseAnalyzer.parseStreamBody(FromClauseAnalyzer.java:319) [classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.FromClauseAnalyzer.parseFromSource(FromClauseAnalyzer.java:247) [classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.FromClauseAnalyzer.createJoinDesc(FromClauseAnalyzer.java:214) [classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.FromClauseAnalyzer.parseJoin(FromClauseAnalyzer.java:178) [classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.FromClauseAnalyzer.parseJoin(FromClauseAnalyzer.java:170) [classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.FromClauseAnalyzer.parseJoinContext(FromClauseAnalyzer.java:135) [classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.FromClauseAnalyzer.parseFromContext(FromClauseAnalyzer.java:128) [classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.FromClauseAnalyzer.analyze(FromClauseAnalyzer.java:92) [classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.SelectStatementAnalyzer.fromAnalyzer(SelectStatementAnalyzer.java:287) [classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.SelectStatementAnalyzer.analyze(SelectStatementAnalyzer.java:93) [classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.SelectStatementAnalyzer.analyze(SelectStatementAnalyzer.java:63) [classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.SelectClauseSemanticAnalyzerTest.testSimpleSelect2(SelectClauseSemanticAnalyzerTest.java:159) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_67]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_67]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_67]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_67]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45) [junit-4.10.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) [junit-4.10.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42) [junit-4.10.jar:na]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263) [junit-4.10.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68) [junit-4.10.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222) [junit-4.10.jar:na]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28) [junit-4.10.jar:na]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300) [junit-4.10.jar:na]
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252) [surefire-junit4-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141) [surefire-junit4-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112) [surefire-junit4-2.12.4.jar:2.12.4]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_67]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_67]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_67]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_67]
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189) [surefire-api-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165) [surefire-booter-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85) [surefire-booter-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115) [surefire-booter-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) [surefire-booter-2.12.4.jar:2.12.4]


2016-08-04 07:06:28 | ERROR | [main] | ERROR CQL-04000: You have an error in your CQL syntax; check the manual that corresponds to your Streaming version for the right syntax to use near 'from' at line 1:8. | com.huawei.streaming.cql.semanticanalyzer.parser.CQLErrorStrategy (CQLErrorListener.java:66) 
com.huawei.streaming.cql.exception.ParseException: ERROR CQL-04000: You have an error in your CQL syntax; check the manual that corresponds to your Streaming version for the right syntax to use near 'from' at line 1:8.
	at com.huawei.streaming.cql.semanticanalyzer.parser.CQLErrorListener.syntaxError(CQLErrorListener.java:61) ~[classes/:na]
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:65) [antlr4-runtime-4.1.jar:4.1]
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:473) [antlr4-runtime-4.1.jar:4.1]
	at com.huawei.streaming.cql.semanticanalyzer.parser.CQLErrorStrategy.reportNoViableAlternative(CQLErrorStrategy.java:60) [classes/:na]
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:145) [antlr4-runtime-4.1.jar:4.1]
	at com.huawei.streaming.cql.semanticanalyzer.parser.CQLParser.selectExpression(CQLParser.java:8166) [classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.parser.CQLParser.selectItem(CQLParser.java:7909) [classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.parser.CQLParser.selectList(CQLParser.java:7852) [classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.parser.CQLParser.subSelectClause(CQLParser.java:7801) [classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.parser.CQLParser.selectClause(CQLParser.java:7746) [classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.parser.CQLParser.selectStatement(CQLParser.java:4811) [classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.parser.CQLParser.execStatement(CQLParser.java:367) [classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.parser.CQLParser.statement(CQLParser.java:248) [classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.parser.ApplicationParser.parse(ApplicationParser.java:61) [classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.parser.ApplicationParserTest.testParse(ApplicationParserTest.java:45) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_67]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_67]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_67]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_67]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45) [junit-4.10.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) [junit-4.10.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42) [junit-4.10.jar:na]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263) [junit-4.10.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68) [junit-4.10.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300) [junit-4.10.jar:na]
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252) [surefire-junit4-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141) [surefire-junit4-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112) [surefire-junit4-2.12.4.jar:2.12.4]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_67]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_67]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_67]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_67]
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189) [surefire-api-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165) [surefire-booter-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85) [surefire-booter-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115) [surefire-booter-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) [surefire-booter-2.12.4.jar:2.12.4]
select  from S
select  from S
You have an error in your CQL syntax; check the manual that corresponds to your Streaming version for the right syntax to use near 'from' at line 1:8.
You have an error in your CQL syntax; check the manual that corresponds to your Streaming version for the right syntax to use near 'from' at line 1:8.
CQL-04000

2016-08-04 07:06:28 | INFO  | [main] | Parse Completed | com.huawei.streaming.cql.semanticanalyzer.parser.ApplicationParser (ApplicationParser.java:69) 
2016-08-04 07:06:28 | ERROR | [main] | Window appear in multi insert clause. | com.huawei.streaming.cql.semanticanalyzer.MultiInsertStatementAnalyzer (MultiInsertStatementAnalyzer.java:198) 
com.huawei.streaming.cql.exception.SemanticAnalyzerException: ERROR CQL-04033: Window is not allowed in multi insert statement.
	at com.huawei.streaming.cql.semanticanalyzer.MultiInsertStatementAnalyzer.windowValidate(MultiInsertStatementAnalyzer.java:196) [classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.MultiInsertStatementAnalyzer.validateSelectStatement(MultiInsertStatementAnalyzer.java:150) [classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.MultiInsertStatementAnalyzer.analyze(MultiInsertStatementAnalyzer.java:95) [classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.MultiInsertStatementAnalyzerTest.testSimpleSelect3(MultiInsertStatementAnalyzerTest.java:125) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_67]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_67]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_67]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_67]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45) [junit-4.10.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) [junit-4.10.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42) [junit-4.10.jar:na]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263) [junit-4.10.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68) [junit-4.10.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222) [junit-4.10.jar:na]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28) [junit-4.10.jar:na]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300) [junit-4.10.jar:na]
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252) [surefire-junit4-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141) [surefire-junit4-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112) [surefire-junit4-2.12.4.jar:2.12.4]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_67]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_67]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_67]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_67]
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189) [surefire-api-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165) [surefire-booter-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85) [surefire-booter-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115) [surefire-booter-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) [surefire-booter-2.12.4.jar:2.12.4]

2016-08-04 07:06:28 | ERROR | [main] | Groupby appear in multi insert clause. | com.huawei.streaming.cql.semanticanalyzer.MultiInsertStatementAnalyzer (MultiInsertStatementAnalyzer.java:180) 
com.huawei.streaming.cql.exception.SemanticAnalyzerException: ERROR CQL-04032: Group by is not allowed in multi insert statement.
	at com.huawei.streaming.cql.semanticanalyzer.MultiInsertStatementAnalyzer.aggregateValidate(MultiInsertStatementAnalyzer.java:178) [classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.MultiInsertStatementAnalyzer.validateSelectStatement(MultiInsertStatementAnalyzer.java:151) [classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.MultiInsertStatementAnalyzer.analyze(MultiInsertStatementAnalyzer.java:95) [classes/:na]
	at com.huawei.streaming.cql.semanticanalyzer.MultiInsertStatementAnalyzerTest.testSimpleSelect4(MultiInsertStatementAnalyzerTest.java:151) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_67]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_67]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_67]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_67]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45) [junit-4.10.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) [junit-4.10.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42) [junit-4.10.jar:na]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263) [junit-4.10.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68) [junit-4.10.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222) [junit-4.10.jar:na]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28) [junit-4.10.jar:na]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30) [junit-4.10.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300) [junit-4.10.jar:na]
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252) [surefire-junit4-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141) [surefire-junit4-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112) [surefire-junit4-2.12.4.jar:2.12.4]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_67]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_67]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_67]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_67]
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189) [surefire-api-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165) [surefire-booter-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85) [surefire-booter-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115) [surefire-booter-2.12.4.jar:2.12.4]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) [surefire-booter-2.12.4.jar:2.12.4]
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 sec

**Comment by Zhiqiang-He** [comment]
这几个都属于异常场景的测试用例，不用关心。主要maven编译成功了，StreamCQL功能就可以正常使用。

**Comment by xiao321** [comment]
3q

**Comment by leopeng1995** [comment]
@Zhiqiang-He @xiao321 我个人建议，在README里，注明测试文件需要配置的环境。如果仅仅只是编译，应该换为`mvn clean install -Dmaven.test.skip=true`，否则就会出现编译错误。

**Comment by Zhiqiang-He** [comment]
上面的其实不是测试失败，而属于异常场景的测试用例，StreamCQL的测试用例都是可以运行成功的，而且运行速度也比较快，所以就没有必要特意说明了。

**Comment by leopeng1995** [comment]
@Zhiqiang-He 嗯，我明白。但因为我git clone下来无法编译成功，测试用例是需要配置相关环境的吧？如果是的话，可以在Quickstart里说明。

**Comment by Zhiqiang-He** [comment]
这个不需要任何配置，可以直接用maven执行编译测试。
