### ISSUE TITLE
storm 1.0.1 updating problems

### ISSUE THREAD

**Issue by 474491418** [HuaweiBigData/StreamCQL#38]
![image](https://cloud.githubusercontent.com/assets/11629195/18502365/53afc258-7a89-11e6-805f-0161092c2abc.png)

When I updated storm from origin version to 1.0.1 that we are using makes the blot’s and spout‘s common component json_conf can not convert  normal as type string ，such as picture，that leads mistake in StormSubmitter and exception show：
2016-09-14 06:53:34 | ERROR | [main] | Failed to parse component resources is:Unexpected character (r) at position 819. | org.apache.storm.scheduler.resource.ResourceUtils (ResourceUtils.java:119) 
org.apache.storm.shade.org.json.simple.parser.ParseException: null
Disconnected from the target VM, address: '127.0.0.1:63511', transport: 'socket'
    at org.apache.storm.shade.org.json.simple.parser.Yylex.yylex(Unknown Source) ~[storm-core-1.0.1.jar:1.0.1]
    at org.apache.storm.shade.org.json.simple.parser.JSONParser.nextToken(Unknown Source) ~[storm-core-1.0.1.jar:1.0.1]
    at org.apache.storm.shade.org.json.simple.parser.JSONParser.parse(Unknown Source) ~[storm-core-1.0.1.jar:1.0.1]
    at org.apache.storm.shade.org.json.simple.parser.JSONParser.parse(Unknown Source) ~[storm-core-1.0.1.jar:1.0.1]
    at org.apache.storm.shade.org.json.simple.parser.JSONParser.parse(Unknown Source) ~[storm-core-1.0.1.jar:1.0.1]
    at org.apache.storm.scheduler.resource.ResourceUtils.parseResources(ResourceUtils.java:100) [storm-core-1.0.1.jar:1.0.1]
    at org.apache.storm.scheduler.resource.ResourceUtils.getBoltsResources(ResourceUtils.java:48) [storm-core-1.0.1.jar:1.0.1]
    at org.apache.storm.StormSubmitter.getMaxExecutorMemoryUsageForTopo(StormSubmitter.java:480) [storm-core-1.0.1.jar:1.0.1]
    at org.apache.storm.StormSubmitter.validateTopologyWorkerMaxHeapSizeMBConfigs(StormSubmitter.java:469) [storm-core-1.0.1.jar:1.0.1]
    at org.apache.storm.StormSubmitter.validateConfs(StormSubmitter.java:465) [storm-core-1.0.1.jar:1.0.1]
    at org.apache.storm.StormSubmitter.submitTopologyAs(StormSubmitter.java:201) [storm-core-1.0.1.jar:1.0.1]
    at org.apache.storm.StormSubmitter.submitTopology(StormSubmitter.java:288) [storm-core-1.0.1.jar:1.0.1]
    at org.apache.storm.StormSubmitter.submitTopology(StormSubmitter.java:155) [storm-core-1.0.1.jar:1.0.1]
    at com.huawei.streaming.storm.StormApplication.submitTopology(StormApplication.java:457) [classes/:na]
    at com.huawei.streaming.storm.StormApplication.remoteLaunch(StormApplication.java:442) [classes/:na]
    at com.huawei.streaming.storm.StormApplication.launch(StormApplication.java:95) [classes/:na]
    at com.huawei.streaming.cql.executor.PhysicalPlanExecutor.submit(PhysicalPlanExecutor.java:187) [classes/:na]
    at com.huawei.streaming.cql.executor.PhysicalPlanExecutor.execute(PhysicalPlanExecutor.java:132) [classes/:na]
    at com.huawei.streaming.cql.tasks.SubmitTask.submitApplication(SubmitTask.java:151) [classes/:na]
    at com.huawei.streaming.cql.tasks.SubmitTask.execute(SubmitTask.java:100) [classes/:na]
    at com.huawei.streaming.cql.Driver.executeTask(Driver.java:199) [classes/:na]
    at com.huawei.streaming.cql.Driver.run(Driver.java:139) [classes/:na]
    at com.huawei.streaming.cql.CQLClient.processCQL(CQLClient.java:264) [classes/:na]
    at com.huawei.streaming.cql.CQLClient.processFile(CQLClient.java:222) [classes/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
    at com.huawei.streaming.cql.CQLClientTest.testSubmit(CQLClientTest.java:78) [test-classes/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45) [junit-4.10.jar:na]
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) [junit-4.10.jar:na]
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42) [junit-4.10.jar:na]
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20) [junit-4.10.jar:na]
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263) [junit-4.10.jar:na]
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68) [junit-4.10.jar:na]
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47) [junit-4.10.jar:na]
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231) [junit-4.10.jar:na]
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60) [junit-4.10.jar:na]
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229) [junit-4.10.jar:na]
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50) [junit-4.10.jar:na]
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222) [junit-4.10.jar:na]
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300) [junit-4.10.jar:na]
    at org.junit.runner.JUnitCore.run(JUnitCore.java:157) [junit-4.10.jar:na]
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78) [junit-rt.jar:na]
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212) [junit-rt.jar:na]
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68) [junit-rt.jar:na]
2016-09-14 06:53:34 | ERROR | [main] | Failed to connect to application server. | com.huawei.streaming.storm.StormApplication (StormApplication.java:477) 
2016-09-14 06:53:34 | INFO  | [main] | delete user packed jar after submit | com.huawei.streaming.cql.executor.PhysicalPlanExecutor (PhysicalPlanExecutor.java:142) 
2016-09-14 06:53:34 | INFO  | [main] | unRegister jars from class loader. | com.huawei.streaming.cql.DriverContext (DriverContext.java:374) 
2016-09-14 06:53:34 | ERROR | [main] | Failed to execute cql  submit application simple
 | com.huawei.streaming.cql.CQLClient (CQLClient.java:270) 
ERROR CQL-99000: An error occurred in CQL Engine.
 submit application simple

**Comment by Zhiqiang-He** [comment]
Storm新版本中的序列化反序列化方式换成JSON方式了，RS是一个schema对象，storm默认不支持。需要检查下storm是如何进行序列化反序列化的，添加schema对象的支持。

**Comment by Zhiqiang-He** [comment]
SimpleJSON只支持简单java对象的序列化反序列化，不支持Pojo类型的序列化，你可以修改CQL代码，在写入schema参数的时候，提前序列化成字符串格式，然后读取的时候再反序列化出来。欢迎提交修改代码。
