### ISSUE TITLE
自定义序列化反序列化类，抛出NotSerializableException异常

### ISSUE THREAD

**Issue by darouwan** [HuaweiBigData/StreamCQL#43]
我正在自己编写一个解析avro的序列化反序列化类，继承自BaseSerDe。
但是在测试过程中，总是抛出如下异常
java.lang.RuntimeException: java.io.NotSerializableException: org.apache.avro.generic.GenericDatumReader

GenericDatumReader是我在解析avro过程中需要用到的一个类。这个类必须在获得schema之后，通过schema解析的结果初始化。无论我在setSchema中初始化，还是在deSerialize或者serialize中初始化，均会抛出不可序列化的异常。那么我应该在哪里初始化无法被序列化的类呢？

**Comment by Zhiqiang-He** [comment]
我看不出来什么原因，是这个类在运行过程中不存在吗？
你可以通过add jar的命令在提交之前手工添加这个文件。

**Comment by darouwan** [comment]
@Zhiqiang-He 是存在的，只是总是抛出无法被序列化的异常。是storm抛出的异常
java.lang.RuntimeException: java.io.NotSerializableException: com.huawei.streaming.serde.GenericDatumWriterSerialable
	at backtype.storm.utils.Utils.javaSerialize(Utils.java:92)
	at backtype.storm.topology.TopologyBuilder.createTopology(TopologyBuilder.java:112)
	at com.huawei.streaming.storm.StormApplication.remoteLaunch(StormApplication.java:552)
	at com.huawei.streaming.storm.StormApplication.launch(StormApplication.java:109)
	at com.huawei.streaming.cql.executor.PhysicalPlanExecutor.submit(PhysicalPlanExecutor.java:209)
	at com.huawei.streaming.cql.executor.PhysicalPlanExecutor.execute(PhysicalPlanExecutor.java:139)
	at com.huawei.streaming.cql.tasks.SubmitTask.submitApplication(SubmitTask.java:167)
	at com.huawei.streaming.cql.tasks.SubmitTask.execute(SubmitTask.java:105)
	at com.huawei.streaming.cql.Driver.executeTask(Driver.java:215)
	at com.huawei.streaming.cql.Driver.run(Driver.java:145)
	at com.huawei.streaming.cql.CQLClient.processCQL(CQLClient.java:304)
	at com.huawei.streaming.cql.CQLClient.processLine(CQLClient.java:238)
	at com.huawei.streaming.cql.CQLClient.readConconsole(CQLClient.java:198)
	at com.huawei.streaming.cql.CQLClient.executeDriver(CQLClient.java:158)
	at com.huawei.streaming.cql.CQLClient.main(CQLClient.java:93)
Caused by: java.io.NotSerializableException: com.huawei.streaming.serde.GenericDatumWriterSerialable
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1183)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
	at backtype.storm.utils.Utils.javaSerialize(Utils.java:88)
	... 14 more

**Comment by Zhiqiang-He** [comment]
确保这个类以及这个类引用的其他类都实现了Serializeable接口。

**Comment by darouwan** [comment]
GenericDatumWriterSerialable是我自己集成了之前的GenericDatumReader类，并implement Serializable接口的一个子类。

**Comment by Zhiqiang-He** [comment]
检查下这个类里面引用的其他类吧，这样的错误肯定是有些类没有实现序列化接口。

**Comment by zhengzf** [comment]
@darouwan 我已经实现了一个，需要的话 我可以上传上来。

**Comment by darouwan** [comment]
@zhengzf 好的，谢谢哦~学习一下

**Comment by zhengzf** [comment]
我看了下跟公司的代码耦合了，剥离比较麻烦，而且我还加了点cql的语法修改，我讲下思路
供参考吧：
可以在cql代码的选项里设置需要用到的类路径，再ser的代码里通过反射创建，解析的
avro数据可以当一个map来处理。
`			Class<?> cl = Utils.getaClass(configStr);
			byte[] tmpArr = (byte[]) data;
			ByteBuf buf = Unpooled.wrappedBuffer(tmpArr);
			BaseConsumerMessage<Object> baseMsg = (BaseConsumerMessage<Object>) messageCode.decode("", buf, cl);
			org.apache.avro.specific.SpecificRecordBase base = (org.apache.avro.specific.SpecificRecordBase) baseMsg
					.getBody();
			//从avro对象中提取字段
			for (String arrt : getSchema().getAllAttributeRawNames()) {
				try {
					Objarrays[i] = Utils.recursioAvronParse(base, arrt);
				} catch (Exception e) {

				}
				i++;
			}`

**Comment by darouwan** [comment]
貌似跟我做法不太一样。我现在用在cql单元测试没问题，现在提交也没问题了，但并没有输出结果~很奇怪

**Comment by darouwan** [comment]
@zhengzf 话说你是如何测试这个插件的？我现在新建了2个stream，s1（avro）和s2，把s1直接导出到s2中打印，也显示不出来

**Comment by zhengzf** [comment]
@darouwan 你直接本地调试好，设置成local模式再ide里调试，断点打在StromBolt里或者你写的插件代码里。

**Comment by darouwan** [comment]
好的谢谢~现在已经全部正常了。还是个别类没有继承Serializable的问题，现在已经修复。
