### ISSUE TITLE
和jstorm使用报错

### ISSUE THREAD

**Issue by dyaodwjh** [HuaweiBigData/StreamCQL#47]
您好:
        我用StreamCQL配合 JSTORM 2.x 使用报错 错误内容如下,请问应该怎么处理呢
2017-01-19 19:19:57,542 | DEBUG | [main] | Simple client transport has been established | backtype.storm.security.auth.SimpleTransportPlugin (SimpleTransportPlugin.java:104)
2017-01-19 19:19:57,562 | ERROR | [main] | Failed to connect to application server. | com.ctrip.streaming.jstorm.JStormApplication (JStormApplication.java:126)
org.apache.thrift7.protocol.TProtocolException: Required field 'supervisors' is unset! Struct:ClusterSummary(supervisors:null, nimbus_uptime_secs:0, topologies:[])
	at backtype.storm.generated.ClusterSummary.validate(ClusterSummary.java:511) ~[storm-core-0.10.2.jar:0.10.2]
	at backtype.storm.generated.ClusterSummary$ClusterSummaryStandardScheme.read(ClusterSummary.java:613) ~[storm-core-0.10.2.jar:0.10.2]
	at backtype.storm.generated.ClusterSummary$ClusterSummaryStandardScheme.read(ClusterSummary.java:549) ~[storm-core-0.10.2.jar:0.10.2]
	at backtype.storm.generated.ClusterSummary.read(ClusterSummary.java:473) ~[storm-core-0.10.2.jar:0.10.2]
	at backtype.storm.generated.Nimbus$getClusterInfo_result$getClusterInfo_resultStandardScheme.read(Nimbus.java:16546) ~[storm-core-0.10.2.jar:0.10.2]
	at backtype.storm.generated.Nimbus$getClusterInfo_result$getClusterInfo_resultStandardScheme.read(Nimbus.java:16531) ~[storm-core-0.10.2.jar:0.10.2]
	at backtype.storm.generated.Nimbus$getClusterInfo_result.read(Nimbus.java:16470) ~[storm-core-0.10.2.jar:0.10.2]
	at org.apache.thrift7.TServiceClient.receiveBase(TServiceClient.java:78) ~[storm-core-0.10.2.jar:0.10.2]
	at backtype.storm.generated.Nimbus$Client.recv_getClusterInfo(Nimbus.java:569) ~[storm-core-0.10.2.jar:0.10.2]
	at backtype.storm.generated.Nimbus$Client.getClusterInfo(Nimbus.java:557) ~[storm-core-0.10.2.jar:0.10.2]
	at com.ctrip.streaming.jstorm.JStormApplication.isApplicationExists(JStormApplication.java:108) [stream-jstorm-2.0.jar:?]
	at com.huawei.streaming.cql.tasks.SubmitTask.checkApplicationExists(SubmitTask.java:172) [cql-2.0.jar:?]
	at com.huawei.streaming.cql.tasks.SubmitTask.dropApplicationIfAllow(SubmitTask.java:158) [cql-2.0.jar:?]
	at com.huawei.streaming.cql.tasks.SubmitTask.execute(SubmitTask.java:106) [cql-2.0.jar:?]
	at com.huawei.streaming.cql.Driver.executeTask(Driver.java:211) [cql-2.0.jar:?]
	at com.huawei.streaming.cql.Driver.run(Driver.java:143) [cql-2.0.jar:?]
	at com.huawei.streaming.cql.CQLClient.processCQL(CQLClient.java:285) [cql-2.0.jar:?]
	at com.huawei.streaming.cql.CQLClient.processFile(CQLClient.java:247) [cql-2.0.jar:?]
	at com.huawei.streaming.cql.CQLClient.executeDriver(CQLClient.java:144) [cql-2.0.jar:?]
	at com.huawei.streaming.cql.CQLClient.main(CQLClient.java:96) [cql-2.0.jar:?]
2017-01-19 19:19:57,566 | INFO  | [main] | unRegister jars from class loader. | com.huawei.streaming.cql.DriverContext (DriverContext.java:423)
2017-01-19 19:19:57,574 | ERROR | [main] | Failed to execute cql SUBMIT APPLICATION cql_example1 | com.huawei.streaming.cql.CQLClient (CQLClient.java:293)

**Comment by Zhiqiang-He** [comment]
Required field 'supervisors' is unset! 
maybe some config is miss. you can add this config in streaming-site.xml.

**Comment by dyaodwjh** [comment]
<property>
                <name>streaming.storm.submit.islocal</name>
                <value>false</value>
                <description></description>
        </property>
        <property>
                <name>streaming.storm.worker.number</name>
                <value>3</value>
                <description></description>
        </property>
         <property>
               <name>streaming.adaptor.application</name>
               <value>com.ctrip.streaming.jstorm.JStormApplication</value>
               <description></description>
         </property>
    <property>
        <name>streaming.killapplication.overtime</name>
        <value>60</value>
        <description></description>
    </property>
        <property>
                <name>streaming.storm.nimbus.host</name>
                <value>10.104.90.xx</value>
                <description></description>
        </property>
        <property>
                <name>streaming.storm.nimbus.port</name>
                <value>8627</value>
                <description></description>
        </property>
        <property>
                <name>streaming.storm.thrift.transport.plugin</name>
                <value>backtype.storm.security.auth.SimpleTransportPlugin</value>
                <description></description>
        </property>
        <property>
                <name>streaming.storm.killtask.waitseconds</name>
                <value>3</value>
                <description></description>
        </property>
    <property>
        <name>streaming.storm.ha.zkaddress</name>
        <value>10.101.22.xx</value>
        <description></description>
    </property>

    <property>
        <name>streaming.storm.ha.zkport</name>
        <value>2181</value>
        <description></description>
    </property>
    <property>
        <name>streaming.serde.default</name>
        <value>com.huawei.streaming.serde.SimpleSerDe</value>
        <description></description>
    </property>
        <property>

这是我现在的配置文件
现在我主要的问题就是不知道这个配置文件还缺失哪个设置
谢谢

**Comment by Zhiqiang-He** [comment]
这个字段在 storm里面来自ClusterSummary。
这是用thrift代码生成的，客户端中没有包含该字段，所以报错，
应该是客户端和服务端的版本不一致导致的。

**Comment by dyaodwjh** [comment]
哦,好的,谢谢
那我换成jstorm-2.1.1试试

**Comment by dyaodwjh** [comment]
你好,我换成了 jstorm-2.1.1 但是还是报 Required field 'supervisors' is unset! Struct:ClusterSummary(supervisors:null, nimbus_uptime_secs:0, topologies:[])

这个异常
请问能不能有个 如何与jstorm 集成配置的教程呢
谢谢

**Comment by Zhiqiang-He** [comment]
这个我也不知道是哪里的问题，我没有用过JStorm，这个JStorm的集成是@zhengzf 贡献的，你可以问下他。在Storm上看到这类问题就是客户端和服务端版本不一致的问题。
你也可以自己调试看下是哪里的问题，欢迎解决之后合入代码。

**Comment by dyaodwjh** [comment]
哦,好的,谢谢
