### ISSUE TITLE
kafkaInput 读取不了数据

### ISSUE THREAD

**Issue by chgxtony** [HuaweiBigData/StreamCQL#51]
CREATE INPUT STREAM s3
    ( c1 STRING)
SOURCE KafkaInput
    PROPERTIES (
        "operator.kafka.groupid" = "cqlClient",
        "operator.kafka.topic" = "cql-storm-topic1",
    "operator.kafka.zookeepers" = "192.168.33.203:2181,192.168.33.204:2181"
        );

然后用kafka-console-producer往这个topic里面写入数据（或者通过其他kafkaOutput输出流来写入），发现kafkaInput无法读取数据，报如下错误

k.c.SimpleConsumer ConsumerFetcherThread-cqlClient_server3-1488266811055-eb4f8744-0-0 [INFO] Reconnect due to error:
java.nio.channels.ClosedChannelException
	at kafka.network.BlockingChannel.send(BlockingChannel.scala:110) ~[stormjar.jar:?]
	at kafka.consumer.SimpleConsumer.liftedTree1$1(SimpleConsumer.scala:85) [stormjar.jar:?]
	at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:83) [stormjar.jar:?]
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(SimpleConsumer.scala:132) [stormjar.jar:?]
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply(SimpleConsumer.scala:132) [stormjar.jar:?]
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply(SimpleConsumer.scala:132) [stormjar.jar:?]
	at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33) [stormjar.jar:?]
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply$mcV$sp(SimpleConsumer.scala:131) [stormjar.jar:?]
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply(SimpleConsumer.scala:131) [stormjar.jar:?]
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply(SimpleConsumer.scala:131) [stormjar.jar:?]
	at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33) [stormjar.jar:?]
	at kafka.consumer.SimpleConsumer.fetch(SimpleConsumer.scala:130) [stormjar.jar:?]
	at kafka.consumer.ConsumerFetcherThread.fetch(ConsumerFetcherThread.scala:111) [stormjar.jar:?]
	at kafka.consumer.ConsumerFetcherThread.fetch(ConsumerFetcherThread.scala:31) [stormjar.jar:?]
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:118) [stormjar.jar:?]
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:103) [stormjar.jar:?]
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63) [stormjar.jar:?]

**Comment by Zhiqiang-He** [comment]
你先执行下StreamCQL首页的kafka的那个例子，看看那个能不能执行，如果没什么问题，就按照那个方式配置下参数。

**Comment by chgxtony** [comment]
那个kafkaOutput是没问题的，KafkaInpu的是有问题的

**Comment by Zhiqiang-He** [comment]
CQL首页也包含了kafka input的参数。

**Comment by chgxtony** [comment]
参数是设置了得，还是有问题。你好，可以加一下你的qq或者微信吗，我给你邮箱发了邮件

**Comment by Zhiqiang-He** [comment]
已经微信给你发送请求了

**Comment by Zhiqiang-He** [comment]
解决了，貌似是配置参数或者版本的问题吧，最终记得不是很清楚了。你可以先用首页的例子试试看有没有问题。

**Comment by sundaytok** [comment]
好的 我试试 谢谢！
