### ISSUE TITLE
为什么两个数据流无法合并。。。。急！求解答

### ISSUE THREAD

**Issue by caiyifeng** [HuaweiBigData/StreamCQL#77]
创建了两个输入流S1,S2,一个输出流rs,使用如下进行数据合并
insert into s_tmp select * from s1;
insert into s_tmp select * from s2;
insert into rs select * from s_tmp;
但在submit的时候老是报错，实在无奈只能求救，报错信息如下：
2018-10-12 00:15:10,126 | INFO  | [main] | Successfully uploaded topology jar to assigned location: /alidata1/admin/jsto_domain/localdata/nimbus/inbox/6f47c866-4fa6-41a4-9196-3db680882188/stormjar-6f47c866-4fa6-41a4-9196-3db680882188.jar | backtype.storm.StormSubmitter (StormSubmitter.java:259) 
2018-10-12 00:15:10,127 | INFO  | [main] | Submitting topology simple in distributed mode with conf {"storm.messaging.netty.min_wait_ms":100,"topology.backpressure.water.mark.high":0.8,"task.kill.wait.seconds":3,"nimbus.classpath":"","storm.zookeeper.auth.user":null,"storm.messaging.netty.buffer_size":5242880,"worker.cpu.core.upper.limit":3,"ui.filter":null,"ui.http.creds.plugin":"backtype.storm.security.auth.DefaultHttpCredentialsPlugin","topology.bolts.outgoing.overflow.buffer.enable":false,"supervisor.supervisors.commands":[],"logviewer.cleanup.age.mins":10080,"supervisor.hostname":null,"topology.tuple.serializer":"backtype.storm.serialization.types.ListDelegateSerializer","topology.master.single.worker":null,"drpc.port":4772,"topology.max.spout.pending":null,"topology.transfer.buffer.size":2048,"logviewer.port":8000,"drpc.childopts":" -Xms1g -Xmx1g -Xmn256m -XX:PermSize=96m -Xmn128m -XX:PermSize=64m -XX:+UseConcMarkSweepGC  -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -XX:CMSFullGCsBeforeCompaction=5 -XX:+HeapDumpOnOutOfMemoryError -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=100M -XX:+UseCMSCompactAtFullCollection -XX:CMSMaxAbortablePrecleanTime=5000 ","nimbus.task.launch.secs":240,"logviewer.childopts":"-Xmx128m","storm.zookeeper.servers":["10.139.32.187"],"topology.alimonitor.topo.metrics.name":"jstorm_metric","storm.messaging.transport":"com.alibaba.jstorm.message.netty.NettyContext","jstorm.log.dir":"\/alidata1\/admin\/jsto_domain\/logs","storm.messaging.netty.authentication":false,"topology.kryo.factory":"backtype.storm.serialization.DefaultKryoFactory","spout.pending.full.sleep":true,"topology.kryo.register.required":false,"container.heartbeat.timeout.seconds":240,"supervisor.slots.ports":null,"supervisor.slots.port.mem.weight":0.7,"topology.stats.sample.rate":0.05,"storm.local.dir":"\/alidata1\/admin\/jsto_domain\/localdata","topology.alimonitor.metrics.post":false,"topology.alimonitor.task.metrics.name":"jstorm_task_metrics","storm.messaging.netty.max_retries":30,"topology.receiver.buffer.size":8,"topology.testing.always.try.serialize":false,"topology.backpressure.check.interval":500,"storm.principal.tolocal":"backtype.storm.security.auth.DefaultPrincipalToLocal","topology.ctrl.buffer.size":256,"java.library.path":"\/usr\/local\/lib:\/opt\/local\/lib:\/usr\/lib","worker.gc.childopts":" -XX:SurvivorRatio=4 -XX:+UseConcMarkSweepGC  -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -XX:CMSFullGCsBeforeCompaction=5 -XX:+HeapDumpOnOutOfMemoryError -XX:+UseCMSCompactAtFullCollection -XX:CMSMaxAbortablePrecleanTime=5000 ","supervisor.slots.port.cpu.weight":0.8,"storm.group.mapping.service.cache.duration.secs":120,"zmq.linger.millis":5000,"topology.multilang.serializer":"backtype.storm.multilang.JsonSerializer","drpc.request.timeout.secs":600,"zmq.threads":1,"topology.state.synchronization.timeout.secs":60,"topology.backpressure.trigger.sample.rate":1,"task.msg.batch.flush.interval.millis":2,"worker.stop.without.supervisor":false,"worker.memory.min.size":null,"topology.worker.shared.thread.pool.size":4,"topology.executor.receive.buffer.size":1024,"supervisor.monitor.frequency.secs":10,"storm.nimbus.retry.times":5,"topology.optimize":true,"transactional.zookeeper.port":null,"storm.auth.simple-white-list.users":[],"storm.zookeeper.port":2181,"storm.zookeeper.retry.intervalceiling.millis":30000,"nimbus.thrift.port":8627,"nimbus.cache.class":null,"supervisor.supervisors":[],"max.match.per.log.search":10,"storm.auth.simple-acl.admins":[],"storm.group.mapping.service":"backtype.storm.security.auth.ShellBasedGroupsMapping","storm.nimbus.retry.interval.millis":2000,"topology.max.task.parallelism":null,"drpc.https.keystore.password":"","storm.messaging.netty.buffer.threshold":8388608,"nimbus.reassign":true,"supervisor.slots.ports.base":6900,"supervisor.heartbeat.frequency.secs":60,"nimbus.credential.renewers.freq.secs":600,"topology.enable.classloader":true,"worker.metric.report.frequency.secs":60,"topology.disruptor.wait.timeout":10,"storm.thrift.transport":"backtype.storm.security.auth.SimpleTransportPlugin","storm.auth.simple-acl.users":[],"supervisor.enable.cgroup":false,"storm.zookeeper.auth.password":null,"ui.port":8080,"drpc.authorizer.acl.strict":false,"topology.message.timeout.secs":30,"topology.error.throttle.interval.secs":10,"drpc.https.keystore.type":"JKS","topology.buffer.size.limited":true,"drpc.authorizer.acl.filename":"drpc-auth-acl.yaml","topology.builtin.metrics.bucket.size.secs":60,"supervisor.frequency.check.secs":60,"storm.local.mode.zmq":false,"supervisor.use.ip":true,"worker.redirect.output":false,"ui.header.buffer.bytes":4096,"process.launcher.enable":true,"storm.machine.resource.reserve.mem":1073741824,"java.sandbox.enable":"false.","process.launcher.childopts":" -Xms256m -Xmx256m  ","drpc.max_buffer_size":31457280,"nimbus.supervisor.timeout.secs":180,"storm.zookeeper.root":"\/jstorm333","zmq.hwm":0,"topology.disruptor.wait.strategy":"com.lmax.disruptor.TimeoutBlockingWaitStrategy","topology.sleep.spout.wait.strategy.time.ms":1,"nimbus.topology.validator":"backtype.storm.nimbus.DefaultTopologyValidator","task.cleanup.timeout.sec":10,"worker.heartbeat.frequency.secs":2,"storm.messaging.netty.max_wait_ms":1000,"container.heartbeat.frequence":10,"topology.max.error.report.per.interval":5,"nimbus.thrift.max_buffer_size":16384000,"topology.backpressure.coordinator.trigger.ratio":0.1,"topology.enable.message.timeouts":true,"storm.messaging.netty.async.block":true,"topology.metric.sample.rate":0.05,"storm.messaging.netty.transfer.batch.size":262144,"task.msg.batch.size":20,"supervisor.run.worker.as.user":false,"storm.messaging.netty.client_worker_threads":1,"topology.tasks":null,"drpc.http.port":3774,"transactional.zookeeper.root":"\/transactional","topology.spout.wait.strategy":"backtype.storm.spout.SleepSpoutWaitStrategy","drpc.servers":["10.139.102.26"],"supervisor.worker.timeout.secs":240,"user.password":null,"topology.worker.receiver.thread.count":1,"nimbus.use.ip":true,"topology.performance.metrics":true,"nimbus.file.copy.expiration.secs":120,"topology.debug.recv.tuple":false,"drpc.http.creds.plugin":"backtype.storm.security.auth.DefaultHttpCredentialsPlugin","worker.classpath":"","storm.machine.resource.panic.check.dir":null,"topology.debug.sample.rate":"1.0d","ui.filter.params":null,"topology.workers":3,"storm.messaging.netty.flush.check.interval.ms":10,"topology.environment":null,"drpc.invocations.port":4773,"supervisor.deamon.logview.encoding":"utf-8","user.name":null,"disruptor.use.sleep":true,"nimbus.cleanup.inbox.freq.secs":600,"topology.fall.back.on.java.serialization":false,"storm.nimbus.retry.intervalceiling.millis":60000,"logviewer.appender.name":"A1","ui.users":null,"storm.machine.resource.reserve.cpu.percent":30,"storm.messaging.netty.server_worker_threads":1,"storm.auth.simple-acl.users.commands":[],"ui.actions.enabled":true,"storm.zookeeper.connection.timeout":30000,"topology.tick.tuple.freq.secs":null,"storm.machine.resource.warning.check.dir":null,"cluster.name":"default","nimbus.inbox.jar.expiration.secs":3600,"storm.machine.resource.error.check.dir":null,"topology.debug":false,"spout.single.thread":false,"storm.zookeeper.retry.interval":1000,"max.blocks.per.log.search":1024,"storm.zookeeper.retry.times":20,"topology.max.worker.num.for.netty.metrics":100,"topology.backpressure.trigger.sample.number":4,"nimbus.host":"10.139.32.185","storm.messaging.netty.disruptor":true,"topology.classpath":null,"cache.timeout.list":null,"task.batch.tuple":true,"user.group":null,"topology.worker.childopts":null,"drpc.https.port":-1,"worker.memory.size":1073741824,"topology.acker.executors":0,"supervisor.worker.start.timeout.secs":120,"supervisor.worker.shutdown.sleep.secs":1,"spout.delay.run":30,"log.page.size":131072,"topology.trident.batch.emit.interval.millis":500,"task.heartbeat.frequency.secs":10,"supervisor.enable":true,"topology.backpressure.enable":true,"drpc.worker.threads":64,"nimbus.cache.reset":true,"storm.messaging.netty.socket.backlog":500,"drpc.queue.size":128,"supervisor.cgroup.rootdir":"jstorm","nimbus.childopts":" -Xms4g -Xmx4g -Xmn1536m -XX:PermSize=256m  -XX:SurvivorRatio=4 -XX:+UseConcMarkSweepGC  -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -XX:CMSFullGCsBeforeCompaction=5 -XX:+HeapDumpOnOutOfMemoryError -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=100M -XX:+UseCMSCompactAtFullCollection -XX:CMSMaxAbortablePrecleanTime=5000 ","topology.backpressure.water.mark.low":0.05,"storm.messaging.netty.max.pending":4,"nimbus.monitor.freq.secs":10,"nimbus.deamon.logview.port":8621,"topology.executor.send.buffer.size":1024,"storm.messaging.netty.sync.mode":false,"transactional.zookeeper.servers":null,"nimbus.task.timeout.secs":240,"logs.users":null,"topology.alimonitor.worker.metrics.name":"jstorm_worker_metrics","topology.alimonitor.user.metrics.name":"jstorm_user_metrics","storm.meta.serialization.delegate":"backtype.storm.serialization.DefaultSerializationDelegate","dev.zookeeper.path":"\/tmp\/dev-storm-zookeeper","storm.messaging.netty.transfer.async.batch":true,"topology.skip.missing.kryo.registrations":false,"supervisor.enable.check":false,"drpc.invocations.threads":64,"storm.zookeeper.session.timeout":30000,"supervisor.deamon.logview.port":8622,"process.launcher.sleep.seconds":20,"topology.timer.update.interval":10,"storm.cluster.mode":"distributed","ui.childopts":" -Xms1g -Xmx1g -Xmn256m -XX:PermSize=96m -XX:+UseConcMarkSweepGC  -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -XX:CMSFullGCsBeforeCompaction=5 -XX:+HeapDumpOnOutOfMemoryError  -XX:+UseCMSCompactAtFullCollection -XX:CMSMaxAbortablePrecleanTime=5000 ","task.refresh.poll.secs":10,"supervisor.childopts":" -Xms1g -Xmx1g -Xmn512m -XX:PermSize=64m -XX:+UseConcMarkSweepGC  -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -XX:CMSFullGCsBeforeCompaction=5 -XX:+HeapDumpOnOutOfMemoryError -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=100M -XX:+UseCMSCompactAtFullCollection -XX:CMSMaxAbortablePrecleanTime=5000 ","topology.task.error.report.interval":60,"task.credentials.poll.secs":30,"worker.redirect.output.file":null} | backtype.storm.StormSubmitter (StormSubmitter.java:122) 
2018-10-12 00:15:10,699 | WARN  | [main] | Failed to assign Fail to sumbit topology Failed to deserilaize Union_011 json configuration: {"streaming.inner.input.stream.name":"st_007","operator.union.inputnames.and.schema":{"st_007":s3,"st_005":s3},"field.define.caseignored":"false","streaming.storm.nimbus.port":"8627","operator.tcpclient.sessiontimeout":"20000","streaming.userfile.maxsize":"50","operator.kafka.zksynctime":"20000","streaming.storm.ha.zksessiontimeout":"30000","operator.headstream.period":"1","operator.headstream.eventnumperperiod":"1","serde.binaryserde.decimaltype":"DECIMAL","streaming.security.zookeeper.principal":"zookeeper\/hadoop","streaming.storm.ha.zkaddress":"10.139.32.187","streaming.serde.default":"com.huawei.streaming.serde.SimpleSerDe","streaming.inner.output.stream.name":"st_003","operator.headstream.delaytime":"0","operator.kafka.messageserializerclass":"kafka.serializer.StringEncoder","operator.kafka.zksessiontimeout":"20000","datasource.rdb.decrypttype":"ALL","serde.keyvalueserde.separator":",","serde.field.ismapping":"false","streaming.storm.worker.number":"1","streaming.killapplication.overtime":"30","streaming.security.storm.principal":"streaming\/hadoop@HADOOP.COM","streaming.inner.input.schema":"rO0ABXNyACljb20uaHVhd2VpLnN0cmVhbWluZy5ldmVudC5UdXBsZUV2ZW50VHlwZTqNoJEQsNqiAgAGSQAEc2l6ZVsACGF0dE5hbWVzdAATW0xqYXZhL2xhbmcvU3RyaW5nO1sACGF0dFR5cGVzdAASW0xqYXZhL2xhbmcvQ2xhc3M7TAAFYXR0aWR0ABNMamF2YS91dGlsL0hhc2hNYXA7TAAEbmFtZXQAEkxqYXZhL2xhbmcvU3RyaW5nO1sABnNjaGVtYXQAJ1tMY29tL2h1YXdlaS9zdHJlYW1pbmcvZXZlbnQvQXR0cmlidXRlO3hwAAAAA3VyABNbTGphdmEubGFuZy5TdHJpbmc7rdJW5+kde0cCAAB4cAAAAAN0AANrZXl0AAV2YWx1ZXQAB3hfY29sXzB1cgASW0xqYXZhLmxhbmcuQ2xhc3M7qxbXrsvNWpkCAAB4cAAAAAN2cgAQamF2YS5sYW5nLlN0cmluZ6DwpDh6O7NCAgAAeHBxAH4AD3ZyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHBzcgARamF2YS51dGlsLkhhc2hNYXAFB9rBwxZg0QMAAkYACmxvYWRGYWN0b3JJAAl0aHJlc2hvbGR4cD9AAAAAAAAMdwgAAAAQAAAAA3EAfgALc3EAfgAQAAAAAnEAfgAKc3EAfgAQAAAAAXEAfgAJc3EAfgAQAAAAAHh0AAJzM3VyACdbTGNvbS5odWF3ZWkuc3RyZWFtaW5nLmV2ZW50LkF0dHJpYnV0ZTtYTmKyXAn7QwIAAHhwAAAAA3NyACRjb20uaHVhd2VpLnN0cmVhbWluZy5ldmVudC5BdHRyaWJ1dGV08W5PK8YBKwIAAkwAC2F0dERhdGFUeXBldAARTGphdmEvbGFuZy9DbGFzcztMAAdhdHROYW1lcQB+AAR4cHEAfgAPcQB+AAlzcQB+ABtxAH4AD3EAfgAKc3EAfgAbcQB+ABJxAH4ACw==","streaming.storm.ha.zkroot":"\/jstorm333","operator.kafka.zookeepers":"127.0.0.1:2181","streaming.security.authentication":"NONE","streaming.storm.rebalance.waitseconds":"10","streaming.operator.timezone":"Asia\/Shanghai","streaming.adaptor.application":"com.ctrip.streaming.jstorm.JStormApplication","streaming.storm.thrift.transport.plugin":"backtype.storm.security.auth.SimpleTransportPlugin","serde.simpleserde.separator":",","operator.kafka.read.frombeginning":"false","operator.kafka.brokers":"127.0.0.1:21802","streaming.inner.output.schema":"rO0ABXNyACljb20uaHVhd2VpLnN0cmVhbWluZy5ldmVudC5UdXBsZUV2ZW50VHlwZTqNoJEQsNqiAgAGSQAEc2l6ZVsACGF0dE5hbWVzdAATW0xqYXZhL2xhbmcvU3RyaW5nO1sACGF0dFR5cGVzdAASW0xqYXZhL2xhbmcvQ2xhc3M7TAAFYXR0aWR0ABNMamF2YS91dGlsL0hhc2hNYXA7TAAEbmFtZXQAEkxqYXZhL2xhbmcvU3RyaW5nO1sABnNjaGVtYXQAJ1tMY29tL2h1YXdlaS9zdHJlYW1pbmcvZXZlbnQvQXR0cmlidXRlO3hwAAAAA3VyABNbTGphdmEubGFuZy5TdHJpbmc7rdJW5+kde0cCAAB4cAAAAAN0AANrZXl0AAV2YWx1ZXQAB3hfY29sXzB1cgASW0xqYXZhLmxhbmcuQ2xhc3M7qxbXrsvNWpkCAAB4cAAAAAN2cgAQamF2YS5sYW5nLlN0cmluZ6DwpDh6O7NCAgAAeHBxAH4AD3ZyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHBzcgARamF2YS51dGlsLkhhc2hNYXAFB9rBwxZg0QMAAkYACmxvYWRGYWN0b3JJAAl0aHJlc2hvbGR4cD9AAAAAAAAMdwgAAAAQAAAAA3EAfgALc3EAfgAQAAAAAnEAfgAKc3EAfgAQAAAAAXEAfgAJc3EAfgAQAAAAAHh0AAJzM3VyACdbTGNvbS5odWF3ZWkuc3RyZWFtaW5nLmV2ZW50LkF0dHJpYnV0ZTtYTmKyXAn7QwIAAHhwAAAAA3NyACRjb20uaHVhd2VpLnN0cmVhbWluZy5ldmVudC5BdHRyaWJ1dGV08W5PK8YBKwIAAkwAC2F0dERhdGFUeXBldAARTGphdmEvbGFuZy9DbGFzcztMAAdhdHROYW1lcQB+AAR4cHEAfgAPcQB+AAlzcQB+ABtxAH4AD3EAfgAKc3EAfgAbcQB+ABJxAH4ACw==","streaming.common.istestmodel":"true","datasource.rdb.decryptclass":"com.huawei.streaming.encrypt.DefaultDecrypt","operator.union.inner.inputnames.and.expression":{"st_007":[Lcom.huawei.streaming.expression.IExpression;@420bc288,"st_005":[Lcom.huawei.streaming.expression.IExpression;@df5f5c0},"streaming.storm.nimbus.host":"10.139.32.185","operator.headstream.totalnumber":"0","streaming.storm.ha.zkport":"2181","streaming.localtask.alivetime.ms":"5000","streaming.storm.killtask.waitseconds":"3","streaming.template.directory":"C:\\Users\\CAIYIF~1\\AppData\\Local\\Temp\\","serde.binaryserde.timetype":"LONG","operator.headstream.isschedule":"false","streaming.storm.ha.zkconnectiontimeout":"30000","operator.consoleprint.frequence":"1","streaming.storm.submit.islocal":"false","operator.headstream.timeunit":"SECONDS"}, cause:null

topologyId:simple-163-1539274510, uploadedJarLocation:/alidata1/admin/jsto_domain/localdata/nimbus/inbox/6f47c866-4fa6-41a4-9196-3db680882188
 | backtype.storm.StormSubmitter (StormSubmitter.java:141) 
backtype.storm.generated.TopologyAssignException
	at backtype.storm.generated.Nimbus$submitTopology_result$submitTopology_resultStandardScheme.read(Nimbus.java:6732) ~[jstorm-core-2.1.1.jar:?]
	at backtype.storm.generated.Nimbus$submitTopology_result$submitTopology_resultStandardScheme.read(Nimbus.java:6700) ~[jstorm-core-2.1.1.jar:?]
	at backtype.storm.generated.Nimbus$submitTopology_result.read(Nimbus.java:6634) ~[jstorm-core-2.1.1.jar:?]
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78) ~[libthrift-0.9.2.jar:0.9.2]
	at backtype.storm.generated.Nimbus$Client.recv_submitTopology(Nimbus.java:243) ~[jstorm-core-2.1.1.jar:?]
	at backtype.storm.generated.Nimbus$Client.submitTopology(Nimbus.java:227) ~[jstorm-core-2.1.1.jar:?]
	at backtype.storm.StormSubmitter.submitTopology(StormSubmitter.java:127) [jstorm-core-2.1.1.jar:?]
	at backtype.storm.StormSubmitter.submitTopology(StormSubmitter.java:59) [jstorm-core-2.1.1.jar:?]
	at com.ctrip.streaming.jstorm.JStormApplication.submitTopology(JStormApplication.java:445) [classes/:?]
	at com.ctrip.streaming.jstorm.JStormApplication.remoteLaunch(JStormApplication.java:439) [classes/:?]
	at com.ctrip.streaming.jstorm.JStormApplication.launch(JStormApplication.java:94) [classes/:?]

**Comment by caiyifeng** [comment]
？？？？？？？？？有人在维护这个开源代码，，求指导。。。。。。。

**Comment by Zhiqiang-He** [comment]
抱歉回复晚了。STORM新版本客户端参数序列化和反序列化方式有修改，参数不支持对象，需要将这些参数的序列化方式进行修改，可以参照streaming.inner.input.schema。

**Comment by Zhiqiang-He** [comment]
这里有问题的参数是operator.union.inner.inputnames.and.expression

**Comment by caiyifeng** [comment]
> 这里有问题的参数是operator.union.inner.inputnames.and.expression

多谢多谢,,我昨天定位到问题了，，已经修改，目前可以用了，，非常感谢！！
