### ISSUE TITLE
com.huawei.streaming.cql.Driver开发语法异常

### ISSUE THREAD

**Issue by pujianfeng** [HuaweiBigData/StreamCQL#79]
你好！我在使用Driver的run方法时，提交的cql语句为首页的kafkacql语句，但是报错为使用“；”导致语法错误，具体报错如下:
2018-11-26 15:05:17,551 | INFO  | [main] | start to parse cql : CREATE INPUT STREAM s1
    (name STRING)
SOURCE RANDOMGEN
    PROPERTIES ( "timeUnit" = "SECONDS", "period" = "1",
        "eventNumPerperiod" = "1", "isSchedule" = "true" );

CREATE OUTPUT STREAM s2 
    (c1 STRING)
SINK kafkaOutput
    PROPERTIES ( "topic" = "cqlOut", "zookeepers" = "127.0.0.1:2181",
        "brokers" = "127.0.0.1:9092" );

CREATE INPUT STREAM s3
    ( c1 STRING)
SOURCE KafkaInput
    PROPERTIES ("groupId" = "cqlClient", "topic" = "cqlOut",
        "zookeepers" = "127.0.0.1:2181", "brokers" = "127.0.0.1:9092" );

CREATE OUTPUT STREAM s4
    (c1 STRING)
SINK consoleOutput;

INSERT INTO STREAM s2 SELECT * FROM s1;
INSERT INTO STREAM s4 SELECT * FROM s3;

SUBMIT APPLICATION cql_kafka_example; | com.huawei.streaming.cql.semanticanalyzer.parser.ApplicationParser (ApplicationParser.java:44) 
2018-11-26 15:05:17,695 | ERROR | [main] | ERROR CQL-04000: You have an error in your CQL syntax; check the manual that corresponds to your Streaming version for the right syntax to use near ';' at line 5:58. | com.huawei.streaming.cql.semanticanalyzer.parser.CQLErrorStrategy (CQLErrorListener.java:66) 
com.huawei.streaming.cql.exception.ParseException: ERROR CQL-04000: You have an error in your CQL syntax; check the manual that corresponds to your Streaming version for the right syntax to use near ';' at line 5:58.
	at com.huawei.streaming.cql.semanticanalyzer.parser.CQLErrorListener.syntaxError(CQLErrorListener.java:61) [cql-2.0.jar:?]
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:65) [antlr4-runtime-4.1.jar:4.1]
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:473) [antlr4-runtime-4.1.jar:4.1]
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:325) [antlr4-runtime-4.1.jar:4.1]
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:148) [antlr4-runtime-4.1.jar:4.1]
	at com.huawei.streaming.cql.semanticanalyzer.parser.CQLParser.statement(CQLParser.java:313) [cql-2.0.jar:?]
	at com.huawei.streaming.cql.semanticanalyzer.parser.ApplicationParser.parse(ApplicationParser.java:61) [cql-2.0.jar:?]
	at com.huawei.streaming.cql.Driver.run(Driver.java:133) [cql-2.0.jar:?]
	at com.test.cqlTest.test.cqltest(test.java:78) [classes/:?]
	at com.test.cqlTest.test.main(test.java:88) [classes/:?]

**Comment by Zhiqiang-He** [comment]
我这里看不出来，感觉是中文符号的问题，建议调试看下是哪里的问题。另外，CQL解析是逐个SQL解析的，所以5行不一定是从第一个sql开始的第五行，也可能是后面其他sql语句。

**Comment by pujianfeng** [comment]
感谢回复！已确认“;”为英文符号，定位也显示是第一个“;”处。同cql语句在linux系统的./cql下运行成功，但是java中使用Driver的run方法运行cql语句时出现以上错误。引用jar包为cql-2.0.jar,stream-storm-2.0.jar和stream-storm-2.0-jar-with-dependencies.jar。请帮忙确认下是否因为引用jar包不当造成以上错误，我是实在找不出其他错误=_=!!!,以上，谢谢！

**Comment by pujianfeng** [comment]
@Zhiqiang-He 我把相关的符号都检查了一遍还是没发现任何问题。能否帮忙确认下是否是因为我的引用流程有问题导致的以上错误
以下是我的代码
package com.test.cqlTest;

import com.huawei.streaming.cql.Driver;
import com.huawei.streaming.cql.exception.CQLException;
public class test {

	public void cqltest()  {
		Driver driverCql = new Driver();
		String str=
				"CREATE INPUT STREAM s1\r\n" + 
				"(name STRING)\r\n" + 
				"SOURCE RANDOMGEN\r\n" + 
				"PROPERTIES (\"timeUnit\"=\"SECONDS\",\"period\"=\"1\",\r\n" + 
				"\"eventNumPerperiod\"=\"1\",\"isSchedule\"=\"true\")\r\n" +
				";\r\n" + 
				"CREATE OUTPUT STREAM s2\r\n" + 
				"(c1 STRING)\r\n" + 
				"SINK kafkaOutput\r\n" + 
				"PROPERTIES (\"topic\"=\"cqlOut\",\"zookeepers\"=\"127.0.0.1:2181\",\r\n" + 
				"\"brokers\"=\"127.0.0.1:9092\");\r\n" + 
				"\r\n" + 
				"CREATE INPUT STREAM s3\r\n" + 
				"(c1 STRING)\r\n" + 
				"SOURCE KafkaInput\r\n" + 
				"PROPERTIES (\"groupId\"=\"cqlClient\",\"topic\"=\"cqlOut\",\r\n" + 
				"\"zookeepers\"=\"127.0.0.1:2181\",\"brokers\"=\"127.0.0.1:9092\");\r\n" + 
				"\r\n" + 
				"CREATE OUTPUT STREAM s4\r\n" + 
				"(c1 STRING)\r\n" + 
				"SINK consoleOutput;\r\n" + 
				"\r\n" + 
				"INSERT INTO STREAM s2 SELECT * FROM s1;\r\n" + 
				"INSERT INTO STREAM s4 SELECT * FROM s3;\r\n" + 
				"\r\n" + 
				"SUBMIT APPLICATION cql_kafka_example;";

		try {

			driverCql.run(str);
			
		} catch (CQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	public static void main(String[] args) {
		test test = new test();
		test.cqltest();
	}
}

以下是错误信息
2018-11-28 13:56:41,351 | INFO  | [main] | start to parse cql : CREATE INPUT STREAM s1
(name STRING)
SOURCE RANDOMGEN
PROPERTIES ("timeUnit"="SECONDS","period"="1",
"eventNumPerperiod"="1","isSchedule"="true")
;
CREATE OUTPUT STREAM s2
(c1 STRING)
SINK kafkaOutput
PROPERTIES ("topic"="cqlOut","zookeepers"="127.0.0.1:2181",
"brokers"="127.0.0.1:9092");

CREATE INPUT STREAM s3
(c1 STRING)
SOURCE KafkaInput
PROPERTIES ("groupId"="cqlClient","topic"="cqlOut",
"zookeepers"="127.0.0.1:2181","brokers"="127.0.0.1:9092");

CREATE OUTPUT STREAM s4
(c1 STRING)
SINK consoleOutput;

INSERT INTO STREAM s2 SELECT * FROM s1;
INSERT INTO STREAM s4 SELECT * FROM s3;

SUBMIT APPLICATION cql_kafka_example; | com.huawei.streaming.cql.semanticanalyzer.parser.ApplicationParser (ApplicationParser.java:44) 
2018-11-28 13:56:41,504 | ERROR | [main] | ERROR CQL-04000: You have an error in your CQL syntax; check the manual that corresponds to your Streaming version for the right syntax to use near ';' at line 6:0. | com.huawei.streaming.cql.semanticanalyzer.parser.CQLErrorStrategy (CQLErrorListener.java:66) 
com.huawei.streaming.cql.exception.ParseException: ERROR CQL-04000: You have an error in your CQL syntax; check the manual that corresponds to your Streaming version for the right syntax to use near ';' at line 6:0.
	at com.huawei.streaming.cql.semanticanalyzer.parser.CQLErrorListener.syntaxError(CQLErrorListener.java:61) [cql-2.0.jar:?]
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:65) [antlr4-runtime-4.1.jar:4.1]
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:473) [antlr4-runtime-4.1.jar:4.1]
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:325) [antlr4-runtime-4.1.jar:4.1]
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:148) [antlr4-runtime-4.1.jar:4.1]
	at com.huawei.streaming.cql.semanticanalyzer.parser.CQLParser.statement(CQLParser.java:313) [cql-2.0.jar:?]
	at com.huawei.streaming.cql.semanticanalyzer.parser.ApplicationParser.parse(ApplicationParser.java:61) [cql-2.0.jar:?]
	at com.huawei.streaming.cql.Driver.run(Driver.java:133) [cql-2.0.jar:?]
	at com.test.cqlTest.test.cqltest(test.java:41) [classes/:?]
	at com.test.cqlTest.test.main(test.java:51) [classes/:?]

**Comment by Zhiqiang-He** [comment]
Driver只允许一次提交一句话，不允许把所有SQL一起提交。你可以对按照分号sql做一个split，然后用driver提交即可。语法本身没有问题，是提交内容不符合语法定义。
注意看下CQLClient.java文件就会发现，命令行下，是逐行解析，并按照分号分隔来提交的。

**Comment by pujianfeng** [comment]
十分感谢，按照以上所述将cql语句用分号split后再用driver提交，未见语法解析异常报错，该问题已解决。
