### ISSUE TITLE
升级到jstorm2.4.0后的问题

### ISSUE THREAD

**Issue by caiyifeng** [HuaweiBigData/StreamCQL#80]
你好：
      我原来用的是jstorm2.1.1版本，用streamingcql进行topology提交都是正常的，，最近升级成了jstorm2.4.0，确发现报错了，，在worker启动进行初始化的时候总是报错如下错误：
----jstorm2.4.0.用的还是backtype.storm.topology.IRichBolt 的，怎么会去找 org.apache.storm.topology.IRichBolt 了呢？？请多指点

java.lang.NoClassDefFoundError: org/apache/storm/topology/IRichBolt
        at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_45]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[na:1.8.0_45]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_45]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_45]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_45]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_45]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_45]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_45]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_45]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_45]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_45]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_45]
        at backtype.storm.utils.WorkerClassLoader.loadClass(WorkerClassLoader.java:92) ~[jstorm-core-2.4.0.jar:na]
        at java.lang.Class.forName0(Native Method) ~[na:1.8.0_45]
        at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_45]
        at shade.storm.org.apache.commons.io.input.ClassLoaderObjectInputStream.resolveClass(ClassLoaderObjectInputStream.java:68) ~[jstorm-core-2.4.
0.jar:na]
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613) ~[na:1.8.0_45]
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518) ~[na:1.8.0_45]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774) ~[na:1.8.0_45]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_45]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371) ~[na:1.8.0_45]
        at backtype.storm.utils.Utils.javaDeserializeWithCL(Utils.java:236) ~[jstorm-core-2.4.0.jar:na]
        at backtype.storm.utils.Utils.getSetComponentObject(Utils.java:514) ~[jstorm-core-2.4.0.jar:na]
        at com.alibaba.jstorm.cluster.Common.get_task_object(Common.java:667) ~[jstorm-core-2.4.0.jar:na]
        at com.alibaba.jstorm.task.Task.<init>(Task.java:149) ~[jstorm-core-2.4.0.jar:na]
        at com.alibaba.jstorm.daemon.worker.Worker.createTasks(Worker.java:115) ~[jstorm-core-2.4.0.jar:na]
        at com.alibaba.jstorm.daemon.worker.Worker.execute(Worker.java:204) ~[jstorm-core-2.4.0.jar:na]
        at com.alibaba.jstorm.daemon.worker.Worker.mk_worker(Worker.java:240) ~[jstorm-core-2.4.0.jar:na]

**Comment by Zhiqiang-He** [comment]
我不确定jstorm2.4.0有什么改动，但是从错误上看起来像是task序列化反序列化的错误，建议把storm版本也一起升级下。
